import type { TranscriptSection } from '../types';

export const MOCK_TRANSCRIPT_DATA: TranscriptSection[] = [
  {
    id: 'section-1',
    title: "Game Start - Ohtani's First Hit",
    startTime: 0,
    endTime: 43,
    sentences: [
      {
        id: 'sent-1',
        text: "but the man right here in sh Otani who's of course never played in the postseason",
        startTime: 0,
        endTime: 5,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-2',
        text: 'and has played in more games than any active player and it needs to be special for those guys',
        startTime: 5,
        endTime: 9,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-3',
        text: 'Otani smokes this ball to right center field Off the Wall',
        startTime: 9,
        endTime: 15,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-4',
        text: "throw from conine is late and it's a screamer of a double to start this ball game",
        startTime: 15,
        endTime: 21,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-5',
        text: 'sh is doing everything he can to get him to the playoffs this is one of those stress relief games',
        startTime: 21,
        endTime: 29,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-6',
        text: 'cuz if you get it done now now things start to fall in order and he was feet away from 49',
        startTime: 29,
        endTime: 34,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-7',
        text: 'there they go throw to third beats him but he got his foot in',
        startTime: 34,
        endTime: 40,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-8',
        text: 'the 50th for Otani',
        startTime: 40,
        endTime: 43,
        isHighlight: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-2',
    title: '50 Stolen Bases Achievement',
    startTime: 43,
    endTime: 91,
    sentences: [
      {
        id: 'sent-9',
        text: 'the accuracy of the slide in all of his bags he has a tendency to read the throw',
        startTime: 43,
        endTime: 50,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-10',
        text: 'understand that the toughest part the tag is the back outside corner and he usually gets it with just his toe and stays on',
        startTime: 50,
        endTime: 58,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-11',
        text: 'sh Otani has stolen 50 bases in his first season with the Dodgers',
        startTime: 58,
        endTime: 67,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-12',
        text: "that's a base hit to right field otani's two for two mun's headed for the plate",
        startTime: 67,
        endTime: 73,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-13',
        text: "conin throws cut off he's got two hits he's got a stolen base he's got a run scored he's got a run batted in",
        startTime: 73,
        endTime: 81,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-14',
        text: "and this game's been going for like 20 minutes this is his version of small ball double and a single",
        startTime: 81,
        endTime: 91,
        isHighlight: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-3',
    title: 'Building Toward the Cycle',
    startTime: 91,
    endTime: 135,
    sentences: [
      {
        id: 'sent-15',
        text: 'One RBI two for two but a nice start to a cycle',
        startTime: 91,
        endTime: 96,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-16',
        text: 'he said to him how about 50/50 how about 51 into second with a stolen base',
        startTime: 96,
        endTime: 103,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-17',
        text: 'is second of the game already how about 660 show we got 10 games left',
        startTime: 103,
        endTime: 109,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-18',
        text: 'slashes his third hit of the game into the left center field Gap looks in to score',
        startTime: 109,
        endTime: 114,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-19',
        text: 'Here Comes pahz Otani heading for third relay is in time',
        startTime: 114,
        endTime: 118,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-20',
        text: 'just shy of finding himself a home run shy of the cycle after three Innings',
        startTime: 118,
        endTime: 126,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-21',
        text: "he'll settle for his third hit in three Innings he's knocked in three",
        startTime: 126,
        endTime: 135,
        isHighlight: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-4',
    title: '49th Home Run - Historic Moment',
    startTime: 135,
    endTime: 184,
    sentences: [
      {
        id: 'sent-22',
        text: 'the one pitch Otani sends one in the air deep right field',
        startTime: 135,
        endTime: 139,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-23',
        text: "he's in a world of his own",
        startTime: 139,
        endTime: 147,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-24',
        text: 'and 135 years of Dodger baseball sh Otani his 49 home runs',
        startTime: 147,
        endTime: 154,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-25',
        text: 'matching Shawn Green for the most in a single season',
        startTime: 154,
        endTime: 159,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-26',
        text: "and he's one shy of the first 5050 campaign in baseball history",
        startTime: 159,
        endTime: 165,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-27',
        text: 'an amazing blast Majestic the second deck',
        startTime: 165,
        endTime: 172,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-28',
        text: 'anything think back to him trying to turn that double into a triple all would have taken was a less than perfect relay',
        startTime: 172,
        endTime: 178,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-29',
        text: 'and this would have been for the cycle',
        startTime: 178,
        endTime: 184,
        isHighlight: false,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-5',
    title: 'The Historic 50-50 Moment',
    startTime: 184,
    endTime: 235,
    sentences: [
      {
        id: 'sent-30',
        text: 'on a onew Otani sends one in the air the other way back it goes',
        startTime: 184,
        endTime: 191,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-31',
        text: 'gone what of a Kind player what of a Kind season',
        startTime: 191,
        endTime: 195,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-32',
        text: 'sh Otani starts the 5050 Club',
        startTime: 195,
        endTime: 202,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-33',
        text: 'the first Dodger with 50 in a season is the first player in the history of this sport',
        startTime: 202,
        endTime: 208,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-34',
        text: "of America's pastime to have 50 home runs and 50 stolen bases in the same season",
        startTime: 208,
        endTime: 213,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-35',
        text: "show Otani has reached 50 and he's reached 50 on the same day",
        startTime: 213,
        endTime: 221,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-36',
        text: 'September 19th 2024 something this game has never seen',
        startTime: 221,
        endTime: 228,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-37',
        text: "otani's done it 5050 are watching this guy oh my gosh",
        startTime: 228,
        endTime: 235,
        isHighlight: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-6',
    title: 'Greatest Day in Baseball History',
    startTime: 235,
    endTime: 319,
    sentences: [
      {
        id: 'sent-38',
        text: 'sh Otani the greatest day in baseball history',
        startTime: 235,
        endTime: 244,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-39',
        text: 'this is not real life he is not human',
        startTime: 244,
        endTime: 256,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-40',
        text: "I can't even keep up with what the final line is",
        startTime: 256,
        endTime: 261,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-41',
        text: "let's make sure we get this exactly right and then hand it send it straight to Cooper toown",
        startTime: 261,
        endTime: 268,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-42',
        text: 'authenticate this line six for six',
        startTime: 268,
        endTime: 277,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-43',
        text: 'three home runs',
        startTime: 277,
        endTime: 282,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-44',
        text: 'five extra base hits',
        startTime: 282,
        endTime: 286,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-45',
        text: 'four runs scored',
        startTime: 286,
        endTime: 290,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-46',
        text: '10 runs spatted in and a 50/50 club and a trip to the Post season',
        startTime: 290,
        endTime: 300,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-47',
        text: 'all rolled into one riking Miami day have a day',
        startTime: 300,
        endTime: 306,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-48',
        text: 'the 10 RBI the first 10 RBI game in Dodger history',
        startTime: 306,
        endTime: 311,
        isHighlight: true,
        isSelected: false,
      },
      {
        id: 'sent-49',
        text: 'the 16th in baseball history send that still shot to the Hall of Fame',
        startTime: 311,
        endTime: 319,
        isHighlight: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 'section-7',
    title: 'Closing Thoughts',
    startTime: 319,
    endTime: 341,
    sentences: [
      {
        id: 'sent-50',
        text: "there's the cliche that you never know what you're going to see when you go to the park",
        startTime: 319,
        endTime: 334,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-51',
        text: "you got to change that cliche from now on there's one thing you know you'll never see",
        startTime: 334,
        endTime: 340,
        isHighlight: false,
        isSelected: false,
      },
      {
        id: 'sent-52',
        text: 'what you saw today',
        startTime: 340,
        endTime: 341,
        isHighlight: true,
        isSelected: false,
      },
    ],
  },
];
